networks:
  cashbot-network:
    driver: bridge
    ipam:
      driver: default

services:
  cashbot-nginx:
    container_name: cashbot-nginx
    image: nginx
    ports:
      - '8090:80'
    depends_on:
      - cashbot
    volumes:
      - ./src:/var/www
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cashbot-network

  cashbot:
    container_name: cashbot
    build:
      context: docker
      dockerfile: app.Dockerfile
    image: cashbot
    ports:
      - '9090:9000'
    volumes:
      - ./src:/var/www
    networks:
      - cashbot-network

  cashbot-mysql:
    container_name: cashbot-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: cashbot
    ports:
      - '3316:3306'
    volumes:
      - cashbot-mysql-volume:/var/lib/mysql
    networks:
      - cashbot-network

  cashbot-mongo:
    container_name: cashbot-mongo
    image: mongo
    ports:
      - 27027:27017
    volumes:
      - ./src:/var/www
      - cashbot-mongodb-volume:/data/db
    logging:
      driver: none
    networks:
      - cashbot-network

  cashbot-node:
    container_name: cashbot-node
    build:
      context: docker
      dockerfile: node.Dockerfile
    image: cashbot/nodejs
    ports:
      - '5193:5193'
    volumes:
      - ./src:/var/www
    networks:
      - cashbot-network

volumes:
  cashbot-mysql-volume:
  cashbot-mongodb-volume:
